export type ActivityKind = "All activity" | "Quests" | "Habits" | "Skills" | "Achievements";
export type RangeKey = "Last 7 days" | "Last 30 days" | "Last 90 days" | "This year" | "Custom date range";
export type DayRecord = { date: string; xp: number; quests: number; habits: number; skills: number; achievements: number; productiveMinutes: number; consistency: 0 | 1 | 2; };

const xp = [160, 220, 95, 310, 180, 260, 340, 120, 190, 280, 145, 390, 215, 270, 175, 330, 245, 410, 155, 295, 365, 205, 255, 425, 185, 315, 235, 380, 290, 445];
export const dailyRecords: DayRecord[] = xp.map((earned, index) => ({ date: `Jun ${index + 1}`, xp: earned, quests: [1, 2, 0, 2, 1, 2, 3][index % 7], habits: [3, 4, 2, 4, 3, 4, 2][index % 7], skills: [1, 1, 0, 2, 1, 1, 2][index % 7], achievements: index === 11 || index === 23 ? 1 : 0, productiveMinutes: 65 + (index * 19) % 105, consistency: index > 26 ? 0 : ([2, 2, 1, 2, 1, 2, 0][index % 7] as 0 | 1 | 2) }));
export const skillGrowth = [{ name: "Front-End Development", xp: 1140 }, { name: "UI/UX Design", xp: 980 }, { name: "Project Management", xp: 620 }, { name: "Communication", xp: 490 }, { name: "Focus", xp: 430 }, { name: "Fitness", xp: 340 }];
export const attributes = [{ name: "Strength", start: 65, current: 72, source: "Fitness quests" }, { name: "Intelligence", start: 78, current: 86, source: "Skill sessions" }, { name: "Discipline", start: 70, current: 79, source: "Habit chains" }, { name: "Creativity", start: 62, current: 68, source: "Design practice" }, { name: "Focus", start: 73, current: 82, source: "Focus sessions" }, { name: "Communication", start: 56, current: 61, source: "Career quests" }];
export const timeline = [{ label: "Level 12 reached", detail: "10,000 lifetime XP recorded", icon: "level", route: "/dashboard" }, { label: "UI/UX Design upgraded", detail: "Level 7 specialization unlocked", icon: "skill", route: "/skills" }, { label: "14-day focus chain", detail: "New personal consistency record", icon: "record", route: "/habits" }, { label: "Pathfinder unlocked", detail: "Achievement archive updated", icon: "award", route: "/achievements" }];
