import test from "node:test";
import assert from "node:assert/strict";
import { createAccountExport, createCalendarAdapter, exportIcs, flushOfflineQueue, parseIcs, previewImport, queueOfflineMutation } from "../app/settings/integration-engine.ts";

test("ICS round-trip preserves timezone, all-day dates, ownership, and stable IDs",()=>{const events=[{externalId:"tz-1",title:"Focus, deep",startsAt:"2026-08-12T09:00:00",endsAt:"2026-08-12T09:50:00",allDay:false,timezone:"Asia/Beirut",source:"ics",systemOwned:true},{externalId:"day-1",title:"Planning day",startsAt:"2026-08-13",endsAt:"2026-08-14",allDay:true,source:"ics",systemOwned:false}];const parsed=parseIcs(exportIcs(events));assert.equal(parsed.rejected.length,0);assert.equal(parsed.events.length,2);assert.equal(parsed.events[0].timezone,"Asia/Beirut");assert.equal(parsed.events[0].systemOwned,true);assert.equal(parsed.events[1].allDay,true);assert.equal(parsed.events[1].startsAt,"2026-08-13");});
test("ICS duplicate and malformed records are reported without discarding valid records",()=>{const valid="BEGIN:VEVENT\r\nUID:a\r\nDTSTART:20260812T090000Z\r\nDTEND:20260812T100000Z\r\nSUMMARY:A\r\nEND:VEVENT";const result=parseIcs(`BEGIN:VCALENDAR\r\nVERSION:2.0\r\n${valid}\r\n${valid}\r\nBEGIN:VEVENT\r\nUID:b\r\nDTSTART:nope\r\nDTEND:nope\r\nEND:VEVENT\r\nEND:VCALENDAR`);assert.equal(result.events.length,1);assert.deepEqual(result.duplicates,["a"]);assert.equal(result.rejected.length,1);});
test("import preview is non-mutating, detects duplicates, and rejects progression injection",()=>{const source={records:[{id:"q1",title:"Plan"},{id:"q1",title:"Duplicate"}]};const before=structuredClone(source);const preview=previewImport(source);assert.deepEqual(source,before);assert.equal(preview.accepted.length,1);assert.deepEqual(preview.duplicates,["q1"]);assert.equal(previewImport({records:[],xp:9999}).valid,false);assert.match(previewImport({records:[],progression:{coins:4}}).rejected.join(" "),/authoritative progression/);});
test("account export is complete, versioned, and restorable only as sanitized planning",()=>{const exported=createAccountExport({profile:{name:"F"},preferences:{},quests:[{id:"q1",title:"Draft",xp:999,coins:999,status:"completed"}],habits:[],skills:[],activity:[{type:"xp_awarded",amount:999}]});assert.equal(exported.version,1);assert.equal(exported.format,"system-account-export");const preview=previewImport(exported);assert.equal(preview.valid,true);assert.equal(preview.accepted[0].status,"draft");assert.equal("xp" in preview.accepted[0],false);assert.equal("coins" in preview.accepted[0],false);});
test("adapter sync is idempotent and can modify only SYSTEM-owned events",async()=>{const adapter=createCalendarAdapter("google_calendar",true);const owned={externalId:"x",title:"Block",startsAt:"2026-08-12T08:00:00Z",endsAt:"2026-08-12T09:00:00Z",allDay:false,source:"google_calendar",systemOwned:true};const external={...owned,externalId:"y",systemOwned:false};const sync=await adapter.sync([owned,owned,external]);assert.equal(sync.events.length,2);assert.equal(adapter.canMutate(owned),true);assert.equal(adapter.canMutate(external),false);await assert.rejects(()=>createCalendarAdapter("microsoft_outlook",false).authorize(["read_events"]));});
test("offline quick capture deduplicates and syncs once while conflicts remain recoverable",async()=>{const mutation={requestId:"stable-1",accountId:"u1",kind:"quick_capture",payload:{text:"idea"}};let queue=queueOfflineMutation([],mutation);queue=queueOfflineMutation(queue,mutation);assert.equal(queue.length,1);let calls=0;queue=await flushOfflineQueue(queue,async()=>{calls++;return "synced"},new Date());queue=await flushOfflineQueue(queue,async()=>{calls++;return "synced"},new Date());assert.equal(calls,1);assert.equal(queue[0].status,"synced");const conflict=await flushOfflineQueue(queueOfflineMutation([],{...mutation,requestId:"stable-2"}),async()=>"conflict",new Date());assert.equal(conflict[0].status,"conflict");assert.match(conflict[0].error,/Review/);});
