import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const sql=(await readFile(new URL("../supabase/migrations/202608110010_positive_social.sql",import.meta.url),"utf8")).toLowerCase();
test("all social tables enable RLS",()=>{ for(const table of ["ally_connections","social_visibility_rules","blocks","accountability_pacts","pact_members","pact_commitments","guilds","guild_members","cooperative_bosses","cooperative_contributions","cooperative_reward_claims","focus_sessions","focus_participants","encouragement_events","social_preferences","reports"]) assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`)); });
test("visibility is server allowlisted and blocking revokes visibility and notifications",()=>{ assert.match(sql,/can_view_social/); assert.match(sql,/category in \('habits','campaigns','milestones','focus_sessions','achievements','summary_metrics'\)/); assert.match(sql,/delete from public\.social_visibility_rules/); assert.match(sql,/delete from public\.notifications/); });
test("boss settlement is authoritative, verified, capped, and idempotent",()=>{ assert.match(sql,/security definer/); assert.match(sql,/type='quest_completed'/); assert.match(sql,/unique\(boss_id,source_event_id\)/); assert.match(sql,/least\(requested_amount,b\.per_member_cap-prior\)/); assert.match(sql,/on conflict do nothing/); assert.match(sql,/coalesce\(settled_at,now\(\)\)/); });
test("focus and encouragement cannot award attendance progression",()=>{ assert.match(sql,/duration_minutes in \(25,50,75\)/); assert.doesNotMatch(sql,/attendance_xp|focus_xp/); assert.match(sql,/kind in \('cheer','respect','well_done'\)/); assert.match(sql,/rate limit reached/); });
test("leaderboards are opt-in with personal best and hidden rank defaults",()=>{ assert.match(sql,/opted_in boolean not null default false/); assert.match(sql,/leaderboard_scope text not null default 'personal_best'/); assert.match(sql,/hide_rank boolean not null default true/); });
