import test from "node:test";
import assert from "node:assert/strict";
import { applyVisibility, contributeToBoss, createFocusSession, leaveEncounter, privateVisibility, recordCommitment, sendEncouragement, transitionConnection } from "../app/leaderboard/social-engine.ts";

test("social visibility is private by default and forbidden data is never exposed",()=>{ const source={habits:4,achievements:2,notes:"secret",journal_entries:[1],evidence_files:[2],calendar_events:[3],energy:1,ai_conversations:[4]}; assert.deepEqual(applyVisibility(source),{}); assert.deepEqual(applyVisibility(source,{...privateVisibility(),habits:true,achievements:true}),{habits:4,achievements:2}); });
test("ally lifecycle accepts, removes, and blocks while block removes contact",()=>{ assert.equal(transitionConnection("pending","accept").state,"accepted"); assert.equal(transitionConnection("accepted","remove").visible,false); assert.deepEqual(transitionConnection("accepted","block"),{state:"blocked",visible:false,notificationsEnabled:false}); assert.throws(()=>transitionConnection("blocked","accept")); });
test("missed commitments affect only the owner and never progression",()=>{ const result=recordCommitment("a","missed"); assert.equal(result.progressionDelta,0); assert.deepEqual(result.affectedParticipantIds,["a"]); assert.ok(result.recoveryPrompt); });
test("boss contributions are verified, capped, additive, immutable, and settle once",()=>{ let boss={id:"b",target:30,total:18,settled:false,contributions:{a:18},eventIds:[]}; let result=contributeToBoss(boss,{participantId:"a",eventId:"q1",verified:true,amount:20,participantCap:25}); assert.equal(result.appliedAmount,7); assert.equal(result.boss.total,25); boss=result.boss; result=contributeToBoss(boss,{participantId:"b",eventId:"q2",verified:true,amount:8,participantCap:25}); assert.equal(result.rewardSettled,true); assert.equal(result.boss.settled,true); const duplicate=contributeToBoss(result.boss,{participantId:"b",eventId:"q2",verified:true,amount:8,participantCap:25}); assert.equal(duplicate.applied,false); assert.equal(leaveEncounter(result.boss,"a").historicalContribution,25); });
test("focus sessions normalize timezones and attendance grants zero XP",()=>{ const session=createFocusSession({startsAt:"2026-08-11T19:00:00+03:00",durationMinutes:50,intention:"draft"}); assert.equal(session.startsAt,"2026-08-11T16:00:00.000Z"); assert.equal(session.attendanceXp,0); assert.throws(()=>createFocusSession({startsAt:new Date().toISOString(),durationMinutes:30,intention:"no"})); });
test("encouragement is positive-only, rate-limited, and blocked-aware",()=>{ assert.equal(sendEncouragement({kind:"cheer",blocked:false,recentCount:0}).progressionDelta,0); assert.throws(()=>sendEncouragement({kind:"respect",blocked:true,recentCount:0})); assert.throws(()=>sendEncouragement({kind:"well_done",blocked:false,recentCount:5})); });
