"use client";
/* eslint-disable react-hooks/set-state-in-effect -- this component intentionally bridges persistent browser state and the external progression event ledger. */

import { useEffect, useMemo, useRef, useState } from "react";
import { Archive, Award, Bell, Check, ChevronRight, Crown, Gift, Sparkles, Trophy, X, Zap } from "lucide-react";
import { usePlayer, type ActivityEvent } from "./player-store";
import "./feedback-system.css";
import "./feedback-motion.css";

type Kind = "xp" | "level" | "rank" | "skill" | "achievement" | "reward" | "streak" | "system";
type Notice = { id: string; eventId: string; kind: Kind; title: string; message: string; route: string; createdAt: string; read: boolean; archived: boolean; celebrationShown: boolean; metadata?: Record<string, unknown> };
type FeedbackPreferences = { inApp?: boolean; milestones?: boolean; xpAnimations?: boolean; celebrations?: boolean; rewardReveals?: boolean; achievementNotifications?: boolean };
const storageKey = "lifequest.notifications.v1";
const priority: Record<Kind, number> = { rank: 1, level: 2, achievement: 3, reward: 4, skill: 5, streak: 6, xp: 7, system: 8 };
const Icon = ({ kind, size = 17 }: { kind: Kind; size?: number }) => kind === "rank" ? <Crown size={size} /> : kind === "level" ? <Trophy size={size} /> : kind === "achievement" ? <Award size={size} /> : kind === "reward" ? <Gift size={size} /> : kind === "skill" ? <Sparkles size={size} /> : kind === "streak" ? <Zap size={size} /> : kind === "xp" ? <Zap size={size} /> : <Bell size={size} />;

function fromEvent(event: ActivityEvent): Notice | null {
  const metadata = event.metadata ?? {}; const amount = Number(metadata.amount ?? 0);
  if (event.type === "xp_awarded") return { id: `notice:${event.id}`, eventId: event.id, kind: "xp", title: "XP gained", message: `+${amount.toLocaleString()} XP added to your evolution path.`, route: event.route, createdAt: event.occurredAt, read: false, archived: false, celebrationShown: false, metadata };
  if (event.type === "level_up") return { id: `notice:${event.id}`, eventId: event.id, kind: "level", title: "Level increased", message: `You reached Level ${String(metadata.to ?? "?")}.`, route: event.route, createdAt: event.occurredAt, read: false, archived: false, celebrationShown: false, metadata };
  if (event.type === "rank_up") return { id: `notice:${event.id}`, eventId: event.id, kind: "rank", title: "Rank increased", message: `Rank ${String(metadata.from ?? "?")} → ${String(metadata.to ?? "?")}.`, route: event.route, createdAt: event.occurredAt, read: false, archived: false, celebrationShown: false, metadata };
  if (event.type === "achievement_unlocked") return { id: `notice:${event.id}`, eventId: event.id, kind: "achievement", title: "New achievement", message: "A permanent milestone has been unlocked.", route: event.route, createdAt: event.occurredAt, read: false, archived: false, celebrationShown: false, metadata };
  if (event.type === "reward_claimed") return { id: `notice:${event.id}`, eventId: event.id, kind: "reward", title: "Reward received", message: "Your earned reward was secured in the vault.", route: event.route, createdAt: event.occurredAt, read: false, archived: false, celebrationShown: false, metadata };
  if (event.type === "attribute_milestone") return { id: `notice:${event.id}`, eventId: event.id, kind: "skill", title: "Skill increased", message: "A specialization reached its next threshold.", route: event.route, createdAt: event.occurredAt, read: false, archived: false, celebrationShown: false, metadata };
  return null;
}

export function FeedbackSystem() {
  const { state } = usePlayer(); const [notices, setNotices] = useState<Notice[]>([]); const [hydrated, setHydrated] = useState(false); const [preferences, setPreferences] = useState<FeedbackPreferences>({}); const [reduced, setReduced] = useState(false); const [open, setOpen] = useState(false); const [filter, setFilter] = useState<"All" | "Unread" | "Progression" | "Achievements" | "Rewards" | "System">("All"); const [active, setActive] = useState<Notice | null>(null); const closeRef = useRef<HTMLButtonElement>(null); const celebrationCloseRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(storageKey) ?? "[]"); if (Array.isArray(saved)) setNotices(saved); const settings = JSON.parse(localStorage.getItem("lifequest.settings.v1") ?? "{}") as FeedbackPreferences & { reducedMotion?: boolean }; setPreferences(settings); setReduced(window.matchMedia("(prefers-reduced-motion: reduce)").matches || Boolean(settings.reducedMotion)); } catch { setNotices([]); } finally { setHydrated(true); } }, []);
  useEffect(() => { if (hydrated) localStorage.setItem(storageKey, JSON.stringify(notices)); }, [hydrated, notices]);
  useEffect(() => { if (!hydrated || preferences.inApp === false) return; const incoming = state.activity.map(fromEvent).filter((item): item is Notice => Boolean(item)).filter(item => item.kind === "xp" ? preferences.xpAnimations !== false : item.kind === "reward" ? preferences.rewardReveals !== false : item.kind === "achievement" ? preferences.achievementNotifications !== false : ["level", "rank", "skill", "streak"].includes(item.kind) ? preferences.milestones !== false : true); setNotices(current => [...incoming.filter(item => !current.some(existing => existing.eventId === item.eventId)), ...current]); }, [hydrated, preferences, state.activity]);
  const unread = notices.filter(item => !item.read && !item.archived).length;
  useEffect(() => { const handler = (event: MouseEvent) => { const target = (event.target as Element | null)?.closest("button[aria-label*='notification' i]"); if (!target) return; event.preventDefault(); setOpen(true); }; document.addEventListener("click", handler); return () => document.removeEventListener("click", handler); }, []);
  useEffect(() => { document.querySelectorAll<HTMLButtonElement>("button[aria-label*='notification' i]").forEach(button => { button.setAttribute("aria-label", `${unread} unread notifications. Open Notification Center`); const badge = button.querySelector("b"); if (badge) badge.textContent = String(unread); }); }, [unread]);
  useEffect(() => { if (!open) return; closeRef.current?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [open]);
  useEffect(() => { if (!active) return; celebrationCloseRef.current?.focus(); const handler = (event: KeyboardEvent) => { if (event.key === "Escape") { setNotices(current => current.map(item => item.id === active.id ? { ...item, celebrationShown: true, read: true } : item)); setActive(null); } }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [active]);
  useEffect(() => { const pending = notices.filter(item => item.kind === "xp" && !item.celebrationShown && !item.archived); if (!pending.length) return; const timer = window.setTimeout(() => setNotices(current => current.map(item => pending.some(candidate => candidate.id === item.id) ? { ...item, celebrationShown: true, read: true } : item)), 4200); return () => window.clearTimeout(timer); }, [notices]);
  const queue = useMemo(() => notices.filter(item => !item.celebrationShown && !item.archived && item.kind !== "xp" && item.kind !== "system" && preferences.celebrations !== false).toSorted((a, b) => priority[a.kind] - priority[b.kind] || a.createdAt.localeCompare(b.createdAt)), [notices, preferences.celebrations]);
  useEffect(() => { if (!active && queue.length) setActive(queue[0]); }, [active, queue]);
  const mark = (id: string, patch: Partial<Notice>) => setNotices(current => current.map(item => item.id === id ? { ...item, ...patch } : item));
  const dismiss = () => { if (!active) return; mark(active.id, { celebrationShown: true, read: true }); setActive(null); };
  const visible = notices.filter(item => !item.archived && (filter === "All" || filter === "Unread" ? !item.read : filter === "Progression" ? ["xp", "level", "rank", "skill", "streak"].includes(item.kind) : filter === "Achievements" ? item.kind === "achievement" : filter === "Rewards" ? item.kind === "reward" : item.kind === "system"));
  return <><div className="feedback-toast-stack" aria-live="polite">{notices.filter(item => item.kind === "xp" && !item.celebrationShown && !item.archived).slice(0, 3).map(item => <button className="feedback-toast" key={item.id} onClick={() => { mark(item.id, { celebrationShown: true, read: true }); setOpen(true); }}><Icon kind={item.kind} /><span><b>{item.title}</b>{item.message}</span><X size={14} aria-hidden="true" /></button>)}</div>
    {open && <aside className="notification-drawer" role="dialog" aria-modal="true" aria-label="Notification Center"><header><div><p>GLOBAL FEEDBACK</p><h2>Notification Center</h2></div><button ref={closeRef} onClick={() => setOpen(false)} aria-label="Close Notification Center"><X size={19} /></button></header><div className="notification-tabs">{(["All", "Unread", "Progression", "Achievements", "Rewards", "System"] as const).map(item => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}{item === "Unread" && unread ? <b>{unread}</b> : null}</button>)}</div><div className="notification-actions"><button onClick={() => setNotices(current => current.map(item => ({ ...item, read: true })))}><Check size={14} /> Mark all read</button><button onClick={() => setNotices(current => current.filter(item => !item.archived))}><Archive size={14} /> Clear archived</button></div><section className="notification-list">{visible.length ? visible.map(item => <article className={`${item.kind} ${item.read ? "read" : ""}`} key={item.id}><Icon kind={item.kind} /><button className="notice-copy" onClick={() => { mark(item.id, { read: true }); window.location.assign(item.route); }}><b>{item.title}</b><span>{item.message}</span><small>{new Date(item.createdAt).toLocaleString()}</small></button><div><button onClick={() => mark(item.id, { read: true })} aria-label={`Mark ${item.title} as read`}><Check size={14} /></button><button onClick={() => mark(item.id, { archived: true })} aria-label={`Archive ${item.title}`}><Archive size={14} /></button></div></article>) : <div className="notification-empty"><Bell size={25} /><b>No notifications in this signal.</b><span>Verified progress and system updates will appear here.</span></div>}</section></aside>}
    {open && <button className="notification-scrim" onClick={() => setOpen(false)} aria-label="Close Notification Center" />}
    {active && <section className={`celebration-overlay ${active.kind} ${reduced ? "reduced" : ""}`} role="dialog" aria-modal="true" aria-labelledby="celebration-title" aria-describedby="celebration-description"><div className="celebration-orbit" aria-hidden="true" /><button ref={celebrationCloseRef} className="celebration-close" onClick={dismiss} aria-label="Skip celebration"><X size={18} /></button><Icon kind={active.kind} size={34} /><p>{active.kind.toUpperCase()} SIGNAL</p><h2 id="celebration-title">{active.title}</h2><strong>{active.kind === "level" ? `LEVEL ${String(active.metadata?.to ?? "?")}` : active.kind === "rank" ? `RANK ${String(active.metadata?.to ?? "?")}` : active.message}</strong><span id="celebration-description">Your progression is recorded permanently. Review the related system or continue your evolution.</span><div><button onClick={() => window.location.assign(active.route)}>View details <ChevronRight size={15} /></button><button onClick={dismiss}>Continue</button></div></section>}
  </>;
}
