"use client";
/* eslint-disable @next/next/no-img-element, jsx-a11y/no-noninteractive-element-to-interactive-role */

import { ChangeEvent, useMemo, useState } from "react";
import { Award, ChevronRight, Edit3, Flame, Menu, Package, ShieldCheck, Sparkles, Target, Trophy, X } from "lucide-react";
import { Sidebar } from "../dashboard/page";
import { events } from "./data";
import { selectAchievementTotals, selectEquippedItems, selectLeaderboardScore, selectQuestTotals, selectXpProgress, usePlayer } from "../player-store";
import "../dashboard/dashboard.css";
import "./profile.css";

const tabs = ["Overview", "Status", "Collection", "Activity"] as const;
type Tab = typeof tabs[number];

export default function Profile() {
  const { state, updateProfile, allocate } = usePlayer();
  const [tab, setTab] = useState<Tab>("Overview"); const [collapsed, setCollapsed] = useState(false); const [mobile, setMobile] = useState(false);
  const [edit, setEdit] = useState(false); const [preview, setPreview] = useState(false); const [filter, setFilter] = useState("All Activity"); const [pending, setPending] = useState<Record<string, number>>({});
  const spent = Object.values(pending).reduce((sum, value) => sum + value, 0); const xpProgress = selectXpProgress(state); const questTotals = selectQuestTotals(state); const achievementTotals = selectAchievementTotals(state);
  const displayedEvents = useMemo(() => state.activity.length ? state.activity.map(event => ({ type: event.type, label: event.type, detail: new Date(event.occurredAt).toLocaleDateString(), route: event.route })) : events, [state.activity]);
  const visibleEvents = displayedEvents.filter(event => filter === "All Activity" || event.type === filter);
  const upload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !file.type.startsWith("image/") || file.size > 2_000_000) return; const reader = new FileReader(); reader.onload = () => updateProfile({ avatar: String(reader.result) }); reader.readAsDataURL(file); };
  const confirmAllocation = () => { Object.entries(pending).forEach(([id, points]) => allocate(id, points)); setPending({}); };
  return <main className="dashboard-page profile-page"><div className="dashboard-atmosphere" />
    <Sidebar collapsed={collapsed} mobileOpen={mobile} active="" onSelect={() => setMobile(false)} onCollapse={() => setCollapsed(!collapsed)} onClose={() => setMobile(false)} />
    <section className={`dashboard-shell ${collapsed ? "sidebar-collapsed" : ""}`}><header className="dashboard-header"><button className="mobile-menu" onClick={() => setMobile(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumb"><span>SYSTEM /</span> PLAYER PROFILE</div><div className="profile-online">SYSTEM ONLINE <i /> 14 JUN 2026</div></header>
      <div className="profile-content"><section className="identity"><div className="identity-avatar">{state.profile.avatar ? <img src={state.profile.avatar} alt={`${state.profile.displayName} avatar`} /> : state.profile.displayName.slice(0, 1)}<i /></div><div className="identity-copy"><p>PLAYER STATUS / ACTIVE</p><h1>{state.profile.displayName} <em>LV. {state.progression.level}</em></h1><span>@{state.profile.username} · {state.profile.title} · Rank {state.progression.rank}</span><p>{state.profile.bio}</p><small>Member since {new Date(state.profile.memberSince).toLocaleString(undefined, { month: "long", year: "numeric" })} · {state.progression.league}</small><div className="xp"><span>{state.progression.xp.toLocaleString()} <small>/ {state.progression.nextLevelXp.toLocaleString()} XP</small></span><i><b style={{ width: `${Math.round(xpProgress * 100)}%` }} /></i><small>{(state.progression.nextLevelXp - state.progression.xp).toLocaleString()} XP to Level {state.progression.level + 1}</small></div></div><div className="identity-actions"><button onClick={() => setEdit(true)}><Edit3 size={15} /> Edit Profile</button><button onClick={() => setPreview(true)}><ShieldCheck size={15} /> Preview Public Profile</button></div></section>
        <nav className="profile-tabs" role="tablist">{tabs.map(item => <button role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav>
        {tab === "Overview" && <Overview quests={questTotals.completed} achievements={achievementTotals.unlocked} score={selectLeaderboardScore(state)} />}
        {tab === "Status" && <Status pending={pending} setPending={setPending} attributes={state.attributes} available={state.progression.attributePoints} spent={spent} confirm={confirmAllocation} />}
        {tab === "Collection" && <Collection title={state.profile.title} avatar={state.profile.avatar} achievements={achievementTotals.unlocked} />}
        {tab === "Activity" && <Activity filter={filter} setFilter={setFilter} list={visibleEvents} />}
      </div></section>
    {edit && <EditDialog profile={state.profile} upload={upload} save={updateProfile} close={() => setEdit(false)} />}{preview && <PublicPreview close={() => setPreview(false)} />}</main>;
}

function Overview({ quests, achievements, score }: { quests: number; achievements: number; score: number }) { return <><section className="summary-grid">{[["Completed quests", quests], ["Attributes", "6"], ["Achievements", achievements], ["Player score", score.toLocaleString()]].map(([label, value]) => <article className="game-panel" key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</section><section className="profile-grid"><section className="game-panel highlight"><p>STRONGEST SKILLS</p>{["Front-End Development · Lv. 8", "UI/UX Design · Lv. 7", "Project Management · Lv. 5"].map(skill => <span key={skill}><Sparkles size={15} />{skill}<b>Active</b></span>)}<button onClick={() => location.assign("/skills")}>View All Skills <ChevronRight size={14} /></button></section><section className="game-panel highlight"><p>CURRENT MAIN QUEST</p><h2>Finish the portfolio case study</h2><span>2 of 4 milestones complete · +800 XP</span><i><b style={{ width: "50%" }} /></i><button onClick={() => location.assign("/quests")}>Open Quest Log <ChevronRight size={14} /></button></section><section className="game-panel highlight"><p>LATEST ACHIEVEMENT</p><h2><Trophy size={19} /> Pathfinder</h2><span>Rare · unlocked 14 Jun 2026</span><button onClick={() => location.assign("/achievements")}>View Archive <ChevronRight size={14} /></button></section></section></>; }
function Status({ pending, setPending, attributes, available, spent, confirm }: { pending: Record<string, number>; setPending: (next: Record<string, number>) => void; attributes: { id: string; name: string; value: number; level: number }[]; available: number; spent: number; confirm: () => void }) { return <section className="status-panel game-panel"><header><div><p>ATTRIBUTE MATRIX</p><h2>Total power {attributes.reduce((sum, attribute) => sum + attribute.value, 0)} · strongest {attributes.slice().sort((a, b) => b.value - a.value)[0]?.name}</h2></div><b>{available - spent} points available</b></header>{attributes.map(attribute => { const added = pending[attribute.id] || 0; return <div className="attribute-row" key={attribute.id}><span><strong>{attribute.name}</strong><small>Earned through verified growth</small></span><i><b style={{ width: `${Math.min(100, attribute.value + added)}%` }} /></i><em>Lv. {attribute.level} · {attribute.value + added}</em><button disabled={spent >= available} onClick={() => setPending({ ...pending, [attribute.id]: added + 1 })} aria-label={`Add one point to ${attribute.name}`}>+</button></div>; })}<div className="allocation"><span>Real-life activity remains the primary attribute source.</span><button onClick={() => setPending({})}>Cancel</button><button disabled={!spent} onClick={confirm}>Confirm {spent} point{spent > 1 ? "s" : ""}</button></div></section>; }
function Collection({ title, avatar, achievements }: { title: string; avatar: string | null; achievements: number }) { const { state } = usePlayer(); const equipped = selectEquippedItems(state); const cosmetic = equipped.find(item => ["Titles", "Profile Frames", "Themes"].includes(item.kind)); return <section className="collection-grid"><section className="game-panel loadout"><p>ACTIVE LOADOUT</p><div className="cosmetic">{avatar ? <img src={avatar} alt="" /> : "F"}</div><h2>{cosmetic?.kind === "Titles" ? cosmetic.name : title}</h2><span>{equipped.length ? equipped.map(item => item.name).join(" · ") : "No cosmetics equipped"}</span><b><Flame size={14} /> {equipped.find(item => item.kind === "Boosters")?.name ?? "No active boost"}</b><button onClick={() => location.assign("/inventory")}><Package size={15} /> Open Inventory</button></section><section className="game-panel featured"><p>FEATURED ACHIEVEMENTS</p><span><Award size={16} /> {achievements} achievements unlocked<small>Manage your collection</small></span><button onClick={() => location.assign("/achievements")}>Manage featured achievements</button></section></section>; }
function Activity({ filter, setFilter, list }: { filter: string; setFilter: (filter: string) => void; list: { type: string; label: string; detail: string; route: string }[] }) { return <section className="activity-panel game-panel"><header><div><p>ACTIVITY TIMELINE</p><h2>Recent evolution record</h2></div><div>{["All Activity", "Quests", "Habits", "Skills", "Achievements", "Rewards"].map(item => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div></header>{list.length ? list.map(event => <button className="event" onClick={() => location.assign(event.route)} key={`${event.label}-${event.detail}`}><span>{event.type === "Achievements" ? <Trophy size={16} /> : event.type === "Rewards" ? <Package size={16} /> : <Target size={16} />}</span><div><b>{event.label}</b><small>{event.detail}</small></div><ChevronRight size={14} /></button>) : <p>No progress has been recorded yet.</p>}</section>; }
function EditDialog({ profile, upload, save, close }: { profile: { displayName: string; username: string; bio: string; avatar: string | null }; upload: (event: ChangeEvent<HTMLInputElement>) => void; save: (patch: { displayName?: string; username?: string; bio?: string }) => void; close: () => void }) { const [name, setName] = useState(profile.displayName); const [username, setUsername] = useState(profile.username); const [bio, setBio] = useState(profile.bio); return <div className="profile-scrim"><section className="profile-dialog" role="dialog" aria-modal="true" aria-label="Edit player profile"><button onClick={close} aria-label="Close"><X size={17} /></button><h2>Edit Profile</h2><div className="edit-avatar">{profile.avatar ? <img src={profile.avatar} alt="Avatar preview" /> : profile.displayName.slice(0, 1)}</div><label>Avatar image under 2 MB<input type="file" accept="image/*" onChange={upload} /></label><label>Display name<input value={name} maxLength={40} onChange={event => setName(event.target.value)} /></label><label>Username<input value={username} maxLength={30} onChange={event => setUsername(event.target.value)} /></label><label>Biography<textarea value={bio} maxLength={160} onChange={event => setBio(event.target.value)} /></label><button onClick={() => { save({ displayName: name.trim() || profile.displayName, username: username.trim() || profile.username, bio }); close(); }}>Save profile</button></section></div>; }
function PublicPreview({ close }: { close: () => void }) { const { state } = usePlayer(); return <div className="profile-scrim"><section className="profile-dialog public" role="dialog" aria-modal="true" aria-label="Public profile preview"><button onClick={close} aria-label="Close"><X size={17} /></button><p>PUBLIC PROFILE PREVIEW</p><div className="edit-avatar">{state.preferences.showAvatar && state.profile.avatar ? <img src={state.profile.avatar} alt="Public avatar" /> : state.profile.displayName.slice(0, 1)}</div><h2>{state.profile.displayName}</h2><span>{state.profile.title} · {state.preferences.showRank ? `Level ${state.progression.level} · Rank ${state.progression.rank}` : "Progression hidden"}</span><p>{state.preferences.shareAchievements ? "Achievement collection shared" : "Achievement collection hidden"}</p><button onClick={() => location.assign("/settings")}>Privacy settings</button></section></div>; }
