import { Brain, BriefcaseBusiness, Dumbbell, HeartPulse, Lightbulb, ShieldCheck, Users, type LucideIcon } from "lucide-react";

export type SkillStatus = "locked" | "available" | "unlocked" | "progress" | "mastered";
export type SkillCategory = "Strength" | "Intelligence" | "Discipline" | "Creativity" | "Health" | "Social" | "Career";

export type Skill = { id: string; name: string; category: SkillCategory; description: string; status: SkillStatus; level: number; maxLevel: number; xp: number; requiredXp: number; cost: number; prerequisite?: string; benefits: string[]; activities: string[]; nextReward: string; x: number; y: number };
export type CategoryInfo = { name: SkillCategory; icon: LucideIcon; tone: string; level: number; xp: number; requiredXp: number; unlocked: number; total: number; description: string; bonus: string };

export const categories: CategoryInfo[] = [
  { name: "Strength", icon: Dumbbell, tone: "cyan", level: 12, xp: 680, requiredXp: 900, unlocked: 3, total: 5, description: "Build a body that carries your ambition.", bonus: "+8% movement XP" },
  { name: "Intelligence", icon: Brain, tone: "violet", level: 15, xp: 780, requiredXp: 1000, unlocked: 4, total: 5, description: "Turn learning into clear, useful judgment.", bonus: "+10% learning XP" },
  { name: "Discipline", icon: ShieldCheck, tone: "gold", level: 14, xp: 590, requiredXp: 850, unlocked: 3, total: 5, description: "Forge dependable systems and follow-through.", bonus: "+1 streak shield" },
  { name: "Creativity", icon: Lightbulb, tone: "rose", level: 9, xp: 320, requiredXp: 700, unlocked: 2, total: 5, description: "Make space for original work and expression.", bonus: "+6% idea XP" },
  { name: "Health", icon: HeartPulse, tone: "mint", level: 11, xp: 510, requiredXp: 800, unlocked: 3, total: 5, description: "Protect your energy, recovery, and resilience.", bonus: "+8% recovery XP" },
  { name: "Social", icon: Users, tone: "blue", level: 8, xp: 285, requiredXp: 650, unlocked: 2, total: 5, description: "Build meaningful connections and confidence.", bonus: "+5% social XP" },
  { name: "Career", icon: BriefcaseBusiness, tone: "amber", level: 13, xp: 640, requiredXp: 900, unlocked: 3, total: 5, description: "Turn focused work into professional momentum.", bonus: "+9% career XP" },
];

const branch = (category: SkillCategory, items: Omit<Skill, "category">[]) => items.map((item) => ({ ...item, category }));
export const initialSkills: Skill[] = [
  ...branch("Strength", [
    { id: "move", name: "Consistent Movement", description: "Create a movement rhythm you can keep.", status: "unlocked", level: 2, maxLevel: 3, xp: 130, requiredXp: 180, cost: 1, benefits: ["+3% Fitness XP", "+1 Vitality"], activities: ["Complete a 30-minute workout", "Take a 20-minute walk"], nextReward: "Movement streak bonus", x: 80, y: 250 },
    { id: "bodyweight", name: "Bodyweight Training", description: "Master reliable strength with your own body.", status: "progress", level: 1, maxLevel: 3, xp: 90, requiredXp: 150, cost: 1, prerequisite: "move", benefits: ["+2 Strength", "+5% workout XP"], activities: ["Complete 3 circuit rounds", "Log a strength session"], nextReward: "Unlock Strength Foundation", x: 285, y: 140 },
    { id: "foundation", name: "Strength Foundation", description: "Establish a progressive training baseline.", status: "available", level: 0, maxLevel: 3, xp: 0, requiredXp: 220, cost: 2, prerequisite: "bodyweight", benefits: ["+4 Strength", "Weekly training insight"], activities: ["Complete Bodyweight Training II", "Finish two Fitness quests"], nextReward: "Unlock Endurance Training", x: 490, y: 245 },
    { id: "endurance", name: "Endurance Training", description: "Build durable capacity for long campaigns.", status: "locked", level: 0, maxLevel: 3, xp: 0, requiredXp: 300, cost: 3, prerequisite: "foundation", benefits: ["+3 Vitality", "+8% cardio XP"], activities: ["Run or cycle for 45 minutes"], nextReward: "Physical Mastery route", x: 690, y: 120 },
    { id: "mastery", name: "Physical Mastery", description: "Your movement practice becomes second nature.", status: "locked", level: 0, maxLevel: 1, xp: 0, requiredXp: 500, cost: 5, prerequisite: "endurance", benefits: ["+8 Strength", "Mastery title"], activities: ["Master Endurance Training"], nextReward: "Titan of the routine", x: 880, y: 245 },
  ]),
  ...branch("Intelligence", [
    { id: "reading", name: "Focused Reading", description: "Read with intention and retention.", status: "mastered", level: 3, maxLevel: 3, xp: 260, requiredXp: 260, cost: 1, benefits: ["+3 Intelligence", "+8% reading XP"], activities: ["Read 20 pages", "Write learning notes"], nextReward: "Mastered", x: 80, y: 250 },
    { id: "thinking", name: "Critical Thinking", description: "Question assumptions and frame stronger decisions.", status: "available", level: 0, maxLevel: 3, xp: 0, requiredXp: 180, cost: 2, prerequisite: "reading", benefits: ["+2 Intelligence", "+4% planning XP"], activities: ["Complete two Learning quests", "Review a case study"], nextReward: "Unlock Problem Solving", x: 285, y: 140 },
    { id: "problems", name: "Problem Solving", description: "Turn complexity into next actions.", status: "locked", level: 0, maxLevel: 3, xp: 0, requiredXp: 240, cost: 2, prerequisite: "thinking", benefits: ["+3 Intelligence", "Decision clarity"], activities: ["Solve a product challenge"], nextReward: "Deep Learning route", x: 490, y: 245 },
    { id: "learning", name: "Deep Learning", description: "Convert study into lasting capability.", status: "locked", level: 0, maxLevel: 3, xp: 0, requiredXp: 320, cost: 3, prerequisite: "problems", benefits: ["+5 Intelligence", "+10% study XP"], activities: ["Study React for 60 minutes"], nextReward: "Knowledge Mastery route", x: 690, y: 120 },
    { id: "knowledge", name: "Knowledge Mastery", description: "Synthesize knowledge across every realm.", status: "locked", level: 0, maxLevel: 1, xp: 0, requiredXp: 500, cost: 5, prerequisite: "learning", benefits: ["+8 Intelligence", "Sage title"], activities: ["Master Deep Learning"], nextReward: "Mastered", x: 880, y: 245 },
  ]),
  ...branch("Discipline", [
    { id: "morning", name: "Morning Routine", description: "Start each day with a deliberate ritual.", status: "unlocked", level: 2, maxLevel: 3, xp: 150, requiredXp: 180, cost: 1, benefits: ["+2 Discipline"], activities: ["Complete morning ritual"], nextReward: "Daily Consistency route", x: 80, y: 250 },
    { id: "consistency", name: "Daily Consistency", description: "Keep promises to your future self.", status: "progress", level: 1, maxLevel: 3, xp: 120, requiredXp: 160, cost: 1, prerequisite: "morning", benefits: ["+1 streak shield", "+3% habit XP"], activities: ["Complete 5 habits"], nextReward: "Unlock Time Management", x: 285, y: 140 },
    { id: "time", name: "Time Management", description: "Design a day with room for what matters.", status: "available", level: 0, maxLevel: 3, xp: 0, requiredXp: 220, cost: 2, prerequisite: "consistency", benefits: ["+2 Discipline", "+5% focus XP"], activities: ["Plan tomorrow", "Complete a focus block"], nextReward: "Unlock Deep Focus", x: 490, y: 245 },
    { id: "focus", name: "Deep Focus", description: "Guard attention long enough to create momentum.", status: "locked", level: 0, maxLevel: 3, xp: 0, requiredXp: 320, cost: 3, prerequisite: "time", benefits: ["+4 Discipline", "+10% focus XP"], activities: ["Start a 90-minute focus session"], nextReward: "Unbreakable Discipline route", x: 690, y: 120 },
    { id: "unbreakable", name: "Unbreakable Discipline", description: "Your systems hold even under pressure.", status: "locked", level: 0, maxLevel: 1, xp: 0, requiredXp: 500, cost: 5, prerequisite: "focus", benefits: ["+8 Discipline", "Iron Will title"], activities: ["Master Deep Focus"], nextReward: "Mastered", x: 880, y: 245 },
  ]),
  ...branch("Creativity", ["Idea Capture", "Visual Thinking", "Creative Practice", "Original Projects", "Creative Mastery"].map((name, index) => ({ id: `creative-${index}`, name, description: "Build a repeatable creative practice.", status: index === 0 ? "unlocked" : "locked", level: index === 0 ? 1 : 0, maxLevel: index === 4 ? 1 : 3, xp: index === 0 ? 90 : 0, requiredXp: 160 + index * 45, cost: index + 1, prerequisite: index ? `creative-${index - 1}` : undefined, benefits: ["+2 Creativity", "+4% creative XP"], activities: ["Capture one idea", "Create for 30 minutes"], nextReward: index === 4 ? "Mastered" : "New creative route", x: 80 + index * 200, y: index % 2 ? 140 : 245 }))),
  ...branch("Health", ["Hydration Ritual", "Sleep Protocol", "Recovery Rhythm", "Energy Management", "Vitality Mastery"].map((name, index) => ({ id: `health-${index}`, name, description: "Protect the energy that powers your campaign.", status: index === 0 ? "progress" : index === 1 ? "available" : "locked", level: index === 0 ? 1 : 0, maxLevel: index === 4 ? 1 : 3, xp: index === 0 ? 130 : 0, requiredXp: 160 + index * 45, cost: index + 1, prerequisite: index ? `health-${index - 1}` : undefined, benefits: ["+2 Health", "+4% recovery XP"], activities: ["Drink eight glasses of water", "Log sleep"], nextReward: index === 4 ? "Mastered" : "New recovery route", x: 80 + index * 200, y: index % 2 ? 140 : 245 }))),
  ...branch("Social", ["Connection Ritual", "Active Listening", "Clear Expression", "Community Builder", "Social Mastery"].map((name, index) => ({ id: `social-${index}`, name, description: "Invest in people and communicate with confidence.", status: index === 0 ? "unlocked" : index === 1 ? "available" : "locked", level: index === 0 ? 1 : 0, maxLevel: index === 4 ? 1 : 3, xp: index === 0 ? 110 : 0, requiredXp: 160 + index * 45, cost: index + 1, prerequisite: index ? `social-${index - 1}` : undefined, benefits: ["+2 Social", "+4% connection XP"], activities: ["Reach out to a friend", "Practice active listening"], nextReward: index === 4 ? "Mastered" : "New connection route", x: 80 + index * 200, y: index % 2 ? 140 : 245 }))),
  ...branch("Career", ["Portfolio Foundation", "Communication", "Technical Growth", "Leadership", "Career Mastery"].map((name, index) => ({ id: `career-${index}`, name, description: "Turn focused work into visible professional momentum.", status: index === 0 ? "unlocked" : index === 1 ? "progress" : index === 2 ? "available" : "locked", level: index < 2 ? 1 : 0, maxLevel: index === 4 ? 1 : 3, xp: index === 0 ? 145 : index === 1 ? 100 : 0, requiredXp: 170 + index * 50, cost: index + 1, prerequisite: index ? `career-${index - 1}` : undefined, benefits: ["+2 Career", "+5% career XP"], activities: ["Finish portfolio case study", "Apply to three job opportunities"], nextReward: index === 4 ? "Mastered" : "New career route", x: 80 + index * 200, y: index % 2 ? 140 : 245 }))),
];
