"use client";

import { useMemo, useState } from "react";
import { Award, ChevronRight, Frame, Gem, KeyRound, Menu, Package, Search, Shield, Star, Timer, Trash2, Zap, type LucideIcon } from "lucide-react";
import { Sidebar } from "../dashboard/page";
import { selectEquippedItems, usePlayer, type InventoryItem } from "../player-store";
import "../dashboard/dashboard.css";
import "./inventory.css";

const itemPresentation: Record<string, { icon: LucideIcon; description: string; isNew?: boolean }> = {
  xp: { icon: Zap, description: "Doubles base XP from the next completed quest." }, shield: { icon: Shield, description: "Protects one active habit streak from a missed day." }, focus: { icon: Star, description: "Grants bonus XP after a focused work session.", isNew: true }, title: { icon: Award, description: "Earned for maintaining a 30-day habit streak." }, frame: { icon: Frame, description: "Gold profile frame from Unbreakable Discipline." }, theme: { icon: Package, description: "A brighter cyan interface treatment." }, key: { icon: KeyRound, description: "Unlocks one special challenge quest." }, fragment: { icon: Gem, description: "A rare fragment awarded at a major milestone." },
};
const presentationFor = (item: InventoryItem) => itemPresentation[item.id] ?? { icon: Package, description: "A verified reward stored in your vault." };

export default function Inventory() {
  const { state, consumeInventory, equipInventory } = usePlayer();
  const [selectedId, setSelectedId] = useState("xp"); const [tab, setTab] = useState("All Items"); const [query, setQuery] = useState(""); const [collapsed, setCollapsed] = useState(false); const [mobile, setMobile] = useState(false); const [notice, setNotice] = useState("Vault synchronized. All earned rewards are secure.");
  const items = state.inventory; const selected = items.find(item => item.id === selectedId) ?? items[0]; const visible = useMemo(() => items.filter(item => (tab === "All Items" || item.kind === tab) && item.name.toLowerCase().includes(query.toLowerCase())), [items, query, tab]); const equipped = selectEquippedItems(state);
  if (!selected) return null;
  const selectedPresentation = presentationFor(selected); const SelectedIcon = selectedPresentation.icon; const equippable = ["Titles", "Profile Frames", "Themes"].includes(selected.kind);
  const useItem = () => { if (!consumeInventory(selected.id)) { setNotice("This reward is no longer available in your vault."); return; } setNotice(`${selected.name} activated. Its effect is ready for the next eligible action.`); };
  const equip = () => { if (!equipInventory(selected.id)) { setNotice("Only owned rewards can be equipped."); return; } setNotice(`${selected.name} ${selected.equipped ? "unequipped" : "equipped"}. Player loadout updated.`); };
  return <main className="dashboard-page inventory-page"><div className="dashboard-atmosphere" /><Sidebar collapsed={collapsed} mobileOpen={mobile} active="Inventory" onSelect={() => setMobile(false)} onCollapse={() => setCollapsed(!collapsed)} onClose={() => setMobile(false)} />
    <section className={`dashboard-shell ${collapsed ? "sidebar-collapsed" : ""}`}><header className="dashboard-header"><button className="mobile-menu" onClick={() => setMobile(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumb"><span>SYSTEM /</span> INVENTORY</div><div className="vault-time">SYSTEM ONLINE <i /> 14 JUN 2026 · 21:48</div><div className="header-actions"><button className="header-icon" aria-label="Notifications"><Zap size={17} /><b>2</b></button></div></header>
      <div className="vault-content"><section className="vault-hero"><div><p className="eyebrow"><span /> SECURE REWARD STORAGE</p><h1>REWARD <em>VAULT</em></h1><p>Every item stored here was earned through real progress.</p></div><div className="vault-stats"><span>Items <b>{items.reduce((sum, item) => sum + item.quantity, 0)} / 60</b></span><span>Coins <b>{state.progression.coins.toLocaleString()}</b></span><span>Keys <b>{state.progression.keys}</b></span><span>Equipped <b>{equipped.length}</b></span><span>Titles <b>{items.filter(item => item.kind === "Titles").length}</b></span><span>Legendary <b>{items.filter(item => item.rarity === "Legendary").length}</b></span></div><i><b /></i></section>
        <div className="vault-note"><Gem size={16} />{notice}<span><Timer size={14} /> Capacity {Math.round(items.reduce((sum, item) => sum + item.quantity, 0) / 60 * 100)}%</span></div>
        <section className="vault-controls"><div>{["All Items", "Boosters", "Consumables", "Titles", "Profile Frames", "Themes", "Collectibles"].map(item => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><label><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search vault" /></label></section>
        <div className="vault-workspace"><aside className="loadout game-panel"><p className="eyebrow"><span /> ACTIVE LOADOUT</p><div className="vault-avatar">{state.profile.displayName.slice(0, 1)}<i /></div><strong>{state.profile.displayName}</strong><span>{state.profile.title} · Lv. {state.progression.level}</span><section>{["Titles", "Profile Frames", "Themes"].map(kind => { const item = equipped.find(entry => entry.kind === kind); return <span key={kind}><b>{kind === "Profile Frames" ? "Frame" : kind.slice(0, -1)}</b><em>{item?.name ?? "None equipped"}</em></span>; })}</section><h3>Active boosts</h3><p><Zap size={14} /> {equipped.find(item => item.kind === "Boosters")?.name ?? "No active boost"}</p></aside>
          <section className="item-grid game-panel"><header><p className="eyebrow"><span /> INVENTORY MATRIX</p><h2>{visible.length} items in signal</h2></header><div>{visible.map(item => { const { icon: Icon, isNew } = presentationFor(item); return <button className={`item-slot ${item.rarity.toLowerCase()} ${selected.id === item.id ? "selected" : ""} ${item.equipped ? "equipped" : ""}`} onClick={() => setSelectedId(item.id)} key={item.id}><Icon size={25} /><strong>{item.name}</strong><small>{item.rarity} · {item.kind}</small><b>×{item.quantity}</b>{isNew && <i>NEW</i>}</button>; })}</div></section>
          <aside className="item-details game-panel"><div className={`item-emblem ${selected.rarity.toLowerCase()}`}><SelectedIcon size={30} /></div><p className="eyebrow"><span /> {selected.rarity} / {selected.kind}</p><h2>{selected.name}</h2><p>{selectedPresentation.description}</p><section><span>Quantity <b>{selected.quantity}</b></span><span>Source <b>Achievement archive</b></span><span>Earned <b>14 Jun 2026</b></span></section><button disabled={selected.quantity < 1} onClick={equippable ? equip : useItem}>{selected.equipped ? "Unequip" : equippable ? "Equip item" : "Use item"}</button><div><button disabled aria-label="Item source is not available in this local build">View source <ChevronRight size={14} /></button><button disabled aria-label="Archiving items is not available in this local build"><Trash2 size={14} /> Archive</button></div></aside>
        </div></div></section></main>;
}
