-- Part 15: experience preferences, notification budget, privacy consent, deletion grace, and immutable corrections.
create table public.user_experience_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade, mode text not null default 'standard' check(mode in ('minimal','standard','immersive')),
  density text not null default 'comfortable' check(density in ('comfortable','compact')), reduced_motion boolean not null default false,
  animation_intensity text not null default 'standard' check(animation_intensity in ('minimal','reduced','standard','rich')), sound_volume integer not null default 40 check(sound_volume between 0 and 100), celebration_volume integer not null default 55 check(celebration_volume between 0 and 100),
  high_contrast boolean not null default false, color_safe_patterns boolean not null default false, larger_text boolean not null default false,
  time_format text not null default '24' check(time_format in ('12','24')), first_day text not null default 'monday' check(first_day in ('monday','sunday')),
  default_day_mode text not null default 'balanced' check(default_day_mode in ('balanced','focus','recovery')), updated_at timestamptz not null default now()
);
create table public.user_locale_preferences (user_id uuid primary key references auth.users(id) on delete cascade, locale text not null default 'en' check(locale in ('en','ar')), direction text generated always as (case when locale='ar' then 'rtl' else 'ltr' end) stored, timezone text not null default 'UTC', updated_at timestamptz not null default now());
create table public.notification_preferences (
  user_id uuid not null references auth.users(id) on delete cascade, category text not null check(category in ('quest_habit','daily','campaign','rewards','ai','social','integrations')),
  in_app boolean not null default true, push boolean not null default false, email boolean not null default false, quiet_starts_at time not null default '22:00', quiet_ends_at time not null default '08:00',
  timezone text not null default 'UTC', daily_noncritical_limit integer not null default 4 check(daily_noncritical_limit between 0 and 12), bundled boolean not null default true, paused_until timestamptz, updated_at timestamptz not null default now(), primary key(user_id,category)
);
create table public.notification_delivery_log (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, category text not null, channel text not null check(channel in ('in_app','push','email')), priority text not null default 'noncritical' check(priority in ('noncritical','critical_security')), bundle_id uuid, status text not null check(status in ('queued','delivered','suppressed_budget','suppressed_quiet_hours','failed')), delivered_at timestamptz, created_at timestamptz not null default now());
create table public.privacy_consents (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, purpose text not null check(purpose in ('profile_publish','evidence_publish','ai_context','ai_memory','ai_retention','integration_scope','social_visibility')), scope jsonb not null default '{}'::jsonb, granted boolean not null, granted_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now());
create table public.data_deletion_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, status text not null default 'grace_period' check(status in ('grace_period','cancelled','processing','completed')), requested_at timestamptz not null default now(), execute_after timestamptz not null default now()+interval '14 days', cancelled_at timestamptz, reauthenticated_at timestamptz not null, completed_at timestamptz, check(execute_after>=requested_at+interval '14 days'));
create unique index one_active_deletion_request on public.data_deletion_requests(user_id) where status in ('grace_period','processing');
create table public.progression_adjustment_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete restrict, original_event_id uuid references public.activity_events(id) on delete restrict, adjustment_event_id uuid not null unique references public.activity_events(id) on delete restrict, kind text not null check(kind in ('adjustment','reversal')), reason text not null check(char_length(reason) between 10 and 1000), authorized_by uuid not null references auth.users(id) on delete restrict, created_at timestamptz not null default now());

create or replace function public.request_data_deletion(reauthenticated_at timestamptz) returns uuid language plpgsql security definer set search_path=public as $$ declare request_id uuid; begin if reauthenticated_at<now()-interval '10 minutes' then raise exception 'recent re-authentication required'; end if; insert into public.data_deletion_requests(user_id,reauthenticated_at) values(auth.uid(),reauthenticated_at) returning id into request_id; return request_id; end $$;
create or replace function public.cancel_data_deletion(request_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin update public.data_deletion_requests set status='cancelled',cancelled_at=now() where id=request_id and user_id=auth.uid() and status='grace_period' and execute_after>now(); if not found then raise exception 'recoverable request unavailable'; end if; end $$;
create or replace function public.record_progression_adjustment(target_user uuid,original_event uuid,adjustment_kind text,adjustment_metadata jsonb,adjustment_reason text) returns uuid language plpgsql security definer set search_path=public as $$ declare event_id uuid:=gen_random_uuid(); begin if adjustment_kind not in ('adjustment','reversal') or char_length(adjustment_reason)<10 then raise exception 'authorized kind and reason required'; end if; insert into public.activity_events(id,user_id,type,source_id,route,metadata,idempotency_key) values(event_id,target_user,'progression_'||adjustment_kind,original_event::text,'/settings',adjustment_metadata||jsonb_build_object('reason',adjustment_reason,'original_event_id',original_event),adjustment_kind||':'||original_event::text); insert into public.progression_adjustment_events(user_id,original_event_id,adjustment_event_id,kind,reason,authorized_by) values(target_user,original_event,event_id,adjustment_kind,adjustment_reason,auth.uid()); return event_id; end $$;
revoke all on function public.request_data_deletion(timestamptz),public.cancel_data_deletion(uuid),public.record_progression_adjustment(uuid,uuid,text,jsonb,text) from public,anon,authenticated;
grant execute on function public.request_data_deletion(timestamptz),public.cancel_data_deletion(uuid) to authenticated;
grant execute on function public.record_progression_adjustment(uuid,uuid,text,jsonb,text) to service_role;

alter table public.user_experience_preferences enable row level security; alter table public.user_locale_preferences enable row level security; alter table public.notification_preferences enable row level security; alter table public.notification_delivery_log enable row level security; alter table public.privacy_consents enable row level security; alter table public.data_deletion_requests enable row level security; alter table public.progression_adjustment_events enable row level security;
create policy "own experience preferences" on public.user_experience_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own locale preferences" on public.user_locale_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own notification preferences" on public.notification_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own notification delivery log" on public.notification_delivery_log for select using(user_id=auth.uid());
create policy "own privacy consents" on public.privacy_consents for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own deletion requests" on public.data_deletion_requests for select using(user_id=auth.uid());
create policy "own immutable adjustment history" on public.progression_adjustment_events for select using(user_id=auth.uid());
