-- Part 14: secure integration references, portable jobs, and idempotent offline receipts.
create table public.integration_connections (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check(provider in ('google_calendar','microsoft_outlook')), state text not null default 'disconnected' check(state in ('disconnected','connecting','connected','error','revoked')),
  permissions text[] not null default '{}', selected_calendar_external_id text, sync_frequency text not null default 'manual' check(sync_frequency in ('manual','15_minutes','hourly')),
  last_success_at timestamptz, last_error_code text, last_error_message text, disconnected_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,provider)
);
create table public.encrypted_provider_credentials (
  connection_id uuid primary key references public.integration_connections(id) on delete cascade,
  encrypted_access_token bytea not null, encrypted_refresh_token bytea, encryption_key_version integer not null,
  expires_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
comment on table public.encrypted_provider_credentials is 'Server-only envelope-encrypted OAuth material. Never select from browser clients or logs.';
create table public.integration_sync_cursors (connection_id uuid primary key references public.integration_connections(id) on delete cascade, encrypted_cursor bytea, updated_at timestamptz not null default now());
create table public.integration_sync_events (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.integration_connections(id) on delete cascade, direction text not null check(direction in ('import','export')), status text not null check(status in ('started','succeeded','failed','conflict')), imported_count integer not null default 0, exported_count integer not null default 0, duplicate_count integer not null default 0, error_code text, recovery_action text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.external_entity_mappings (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.integration_connections(id) on delete cascade, local_entity_type text not null check(local_entity_type in ('planning_reference','time_block','focus_session')), local_entity_id uuid not null, external_entity_id text not null, external_etag text, system_owned boolean not null default false, last_synced_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(connection_id,external_entity_id),unique(connection_id,local_entity_type,local_entity_id));
create table public.import_jobs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, format text not null check(format in ('system_json_v1','csv','ics')), status text not null default 'preview' check(status in ('preview','confirmed','applied','rejected','failed')), accepted_count integer not null default 0, duplicate_count integer not null default 0, rejected_records jsonb not null default '[]'::jsonb, mapping jsonb not null default '{}'::jsonb, confirmed_at timestamptz, applied_at timestamptz, created_at timestamptz not null default now());
create table public.export_jobs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, format text not null check(format in ('system_json_v1','quests_csv','habits_csv','skills_csv','progression_csv','ics')), status text not null default 'requested' check(status in ('requested','processing','ready','expired','failed')), storage_path text, expires_at timestamptz, created_at timestamptz not null default now());
create table public.offline_mutation_receipts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, client_request_id text not null, mutation_kind text not null check(mutation_kind in ('quick_capture','quest_completion')), entity_id uuid, status text not null check(status in ('settled','conflict','rejected')), result jsonb not null default '{}'::jsonb, settled_at timestamptz not null default now(), unique(user_id,client_request_id));

create or replace function public.disconnect_integration(target_connection uuid,delete_connection_data boolean default true) returns void language plpgsql security definer set search_path=public as $$ begin update public.integration_connections set state='revoked',disconnected_at=now(),updated_at=now() where id=target_connection and user_id=auth.uid(); if not found then raise exception 'connection unavailable'; end if; update public.encrypted_provider_credentials set revoked_at=now(),encrypted_access_token='\x'::bytea,encrypted_refresh_token=null where connection_id=target_connection; if delete_connection_data then delete from public.external_entity_mappings where connection_id=target_connection; delete from public.integration_sync_cursors where connection_id=target_connection; end if; end $$;
create or replace function public.register_external_mapping(target_connection uuid,target_type text,target_local uuid,target_external text,target_etag text,target_system_owned boolean) returns uuid language plpgsql security definer set search_path=public as $$ declare mapping_id uuid; begin if not exists(select 1 from public.integration_connections where id=target_connection and user_id=auth.uid() and state='connected') then raise exception 'connection unavailable'; end if; insert into public.external_entity_mappings(connection_id,local_entity_type,local_entity_id,external_entity_id,external_etag,system_owned) values(target_connection,target_type,target_local,target_external,target_etag,target_system_owned) on conflict(connection_id,external_entity_id) do update set external_etag=excluded.external_etag,updated_at=now() returning id into mapping_id; return mapping_id; end $$;
create or replace function public.assert_system_event_mutation(target_connection uuid,target_external text) returns void language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from public.external_entity_mappings m join public.integration_connections c on c.id=m.connection_id where c.user_id=auth.uid() and m.connection_id=target_connection and m.external_entity_id=target_external and m.system_owned=true) then raise exception 'SYSTEM may modify only its own external events'; end if; end $$;
create or replace function public.settle_offline_mutation(p_request_id text,p_kind text,p_entity_id uuid default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare existing jsonb; result jsonb; begin select r.result into existing from public.offline_mutation_receipts r where r.user_id=auth.uid() and r.client_request_id=p_request_id; if existing is not null then return existing||jsonb_build_object('duplicate',true); end if; if p_kind='quest_completion' then result:=public.complete_quest(p_entity_id,p_request_id); elsif p_kind='quick_capture' then result:=jsonb_build_object('captured',true,'progression_delta',0); else raise exception 'unsupported offline mutation'; end if; insert into public.offline_mutation_receipts(user_id,client_request_id,mutation_kind,entity_id,status,result) values(auth.uid(),p_request_id,p_kind,p_entity_id,'settled',result); return result||jsonb_build_object('duplicate',false); end $$;
revoke all on function public.disconnect_integration(uuid,boolean),public.register_external_mapping(uuid,text,uuid,text,text,boolean),public.assert_system_event_mutation(uuid,text),public.settle_offline_mutation(text,text,uuid) from public,anon;
grant execute on function public.disconnect_integration(uuid,boolean),public.register_external_mapping(uuid,text,uuid,text,text,boolean),public.assert_system_event_mutation(uuid,text),public.settle_offline_mutation(text,text,uuid) to authenticated;

alter table public.integration_connections enable row level security; alter table public.encrypted_provider_credentials enable row level security; alter table public.integration_sync_cursors enable row level security; alter table public.integration_sync_events enable row level security; alter table public.external_entity_mappings enable row level security; alter table public.import_jobs enable row level security; alter table public.export_jobs enable row level security; alter table public.offline_mutation_receipts enable row level security;
create policy "own integration connections" on public.integration_connections for select using(user_id=auth.uid());
create policy "own sync events" on public.integration_sync_events for select using(exists(select 1 from public.integration_connections c where c.id=connection_id and c.user_id=auth.uid()));
create policy "own external mappings" on public.external_entity_mappings for select using(exists(select 1 from public.integration_connections c where c.id=connection_id and c.user_id=auth.uid()));
create policy "own import jobs" on public.import_jobs for all using(user_id=auth.uid()) with check(user_id=auth.uid() and status='preview');
create policy "own export jobs" on public.export_jobs for select using(user_id=auth.uid());
create policy "own offline receipts" on public.offline_mutation_receipts for select using(user_id=auth.uid());
-- No browser policy exists for encrypted credentials or cursors; only server-side functions/service roles can access them.
