-- Part 13: invitation-only social accountability. Private by default.
create table public.ally_connections (
  id uuid primary key default gen_random_uuid(), requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade, status text not null default 'pending' check(status in ('pending','accepted','declined','blocked','removed')),
  blocked_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(requester_id <> addressee_id), unique(requester_id,addressee_id)
);
create table public.social_visibility_rules (
  id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, ally_id uuid not null references auth.users(id) on delete cascade,
  category text not null check(category in ('habits','campaigns','milestones','focus_sessions','achievements','summary_metrics')), visible boolean not null default false,
  unique(owner_id,ally_id,category)
);
create table public.blocks (blocker_id uuid not null references auth.users(id) on delete cascade, blocked_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now(), primary key(blocker_id,blocked_id), check(blocker_id<>blocked_id));
create table public.accountability_pacts (
  id uuid primary key default gen_random_uuid(), creator_id uuid not null references auth.users(id), purpose text not null check(char_length(purpose) between 3 and 240), starts_on date not null, ends_on date not null,
  cadence text not null, visibility text not null default 'members' check(visibility='members'), encouragement_preferences jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), check(ends_on>=starts_on)
);
create table public.pact_members (pact_id uuid not null references public.accountability_pacts(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, state text not null default 'invited' check(state in ('invited','accepted','declined','left')), joined_at timestamptz, primary key(pact_id,user_id));
create table public.pact_commitments (id uuid primary key default gen_random_uuid(), pact_id uuid not null references public.accountability_pacts(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, commitment text not null check(char_length(commitment)<=300), check_in_at timestamptz, status text not null default 'open' check(status in ('open','complete','missed')), recovery_prompted_at timestamptz, created_at timestamptz not null default now());
create table public.guilds (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), name text not null check(char_length(name) between 2 and 80), description text not null default '' check(char_length(description)<=500), rules text not null default '' check(char_length(rules)<=2000), member_limit integer not null default 8 check(member_limit between 2 and 50), privacy text not null default 'invite_only' check(privacy='invite_only'), created_at timestamptz not null default now());
create table public.guild_members (guild_id uuid not null references public.guilds(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member' check(role in ('owner','admin','member')), state text not null default 'invited' check(state in ('invited','active','declined','left','removed')), joined_at timestamptz, left_at timestamptz, primary key(guild_id,user_id));
create table public.cooperative_bosses (id uuid primary key default gen_random_uuid(), guild_id uuid references public.guilds(id) on delete restrict, pact_id uuid references public.accountability_pacts(id) on delete restrict, objective text not null, target integer not null check(target>0), per_member_cap integer not null check(per_member_cap>0), contribution_threshold integer not null default 1 check(contribution_threshold>0), total integer not null default 0 check(total>=0), settled_at timestamptz, created_at timestamptz not null default now(), check((guild_id is null)<>(pact_id is null)));
create table public.cooperative_contributions (id uuid primary key default gen_random_uuid(), boss_id uuid not null references public.cooperative_bosses(id) on delete restrict, user_id uuid not null references auth.users(id) on delete restrict, source_event_id uuid not null references public.activity_events(id) on delete restrict, amount integer not null check(amount>0), created_at timestamptz not null default now(), unique(boss_id,source_event_id));
create table public.cooperative_reward_claims (boss_id uuid not null references public.cooperative_bosses(id) on delete restrict, user_id uuid not null references auth.users(id) on delete restrict, settled_at timestamptz not null default now(), primary key(boss_id,user_id));
create table public.focus_sessions (id uuid primary key default gen_random_uuid(), host_id uuid not null references auth.users(id), starts_at timestamptz not null, duration_minutes integer not null check(duration_minutes in (25,50,75)), visibility text not null default 'invited' check(visibility='invited'), created_at timestamptz not null default now());
create table public.focus_participants (session_id uuid not null references public.focus_sessions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, state text not null default 'invited' check(state in ('invited','accepted','attended','declined','left')), intention text check(char_length(intention)<=240), result text check(char_length(result)<=500), primary key(session_id,user_id));
create table public.encouragement_events (id uuid primary key default gen_random_uuid(), sender_id uuid not null references auth.users(id) on delete cascade, recipient_id uuid not null references auth.users(id) on delete cascade, kind text not null check(kind in ('cheer','respect','well_done')), created_at timestamptz not null default now(), check(sender_id<>recipient_id));
create table public.social_preferences (user_id uuid primary key references auth.users(id) on delete cascade, opted_in boolean not null default false, leaderboard_scope text not null default 'personal_best' check(leaderboard_scope in ('personal_best','allies','guild','season')), hide_rank boolean not null default true, encouragement_notifications boolean not null default true, updated_at timestamptz not null default now());
create table public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references auth.users(id), reported_user_id uuid not null references auth.users(id), context_type text not null check(context_type in ('ally','guild','focus','encouragement')), context_id uuid, reason text not null check(char_length(reason) between 3 and 500), created_at timestamptz not null default now());

create or replace function public.social_blocked(a uuid,b uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.blocks where (blocker_id=a and blocked_id=b) or (blocker_id=b and blocked_id=a)) $$;
create or replace function public.accepted_allies(a uuid,b uuid) returns boolean language sql stable security definer set search_path=public as $$ select not public.social_blocked(a,b) and exists(select 1 from public.ally_connections where status='accepted' and ((requester_id=a and addressee_id=b) or (requester_id=b and addressee_id=a))) $$;
create or replace function public.can_view_social(owner uuid,viewer uuid,requested_category text) returns boolean language sql stable security definer set search_path=public as $$ select owner=viewer or (public.accepted_allies(owner,viewer) and exists(select 1 from public.social_visibility_rules where owner_id=owner and ally_id=viewer and category=requested_category and visible=true)) $$;
create or replace function public.is_guild_member(target_guild uuid,target_user uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.guild_members where guild_id=target_guild and user_id=target_user and state='active') $$;
create or replace function public.is_pact_member(target_pact uuid,target_user uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.pact_members where pact_id=target_pact and user_id=target_user and state='accepted') $$;

create or replace function public.block_player(target uuid) returns void language plpgsql security definer set search_path=public as $$ begin if target=auth.uid() then raise exception 'cannot block self'; end if; insert into public.blocks(blocker_id,blocked_id) values(auth.uid(),target) on conflict do nothing; update public.ally_connections set status='blocked',blocked_by=auth.uid(),updated_at=now() where (requester_id=auth.uid() and addressee_id=target) or (requester_id=target and addressee_id=auth.uid()); delete from public.social_visibility_rules where (owner_id=auth.uid() and ally_id=target) or (owner_id=target and ally_id=auth.uid()); delete from public.notifications where user_id in (auth.uid(),target) and metadata->>'social_peer_id' in (auth.uid()::text,target::text); end $$;
revoke all on function public.block_player(uuid) from public; grant execute on function public.block_player(uuid) to authenticated;

create or replace function public.respond_ally_invite(connection_id uuid,response text) returns void language plpgsql security definer set search_path=public as $$ begin if response not in ('accepted','declined') then raise exception 'invalid response'; end if; update public.ally_connections set status=response,updated_at=now() where id=connection_id and addressee_id=auth.uid() and status='pending' and not public.social_blocked(requester_id,addressee_id); if not found then raise exception 'invite unavailable'; end if; end $$;
create or replace function public.remove_ally(connection_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin update public.ally_connections set status='removed',updated_at=now() where id=connection_id and status='accepted' and auth.uid() in (requester_id,addressee_id); if not found then raise exception 'connection unavailable'; end if; delete from public.social_visibility_rules where owner_id=auth.uid() and ally_id in (select case when requester_id=auth.uid() then addressee_id else requester_id end from public.ally_connections where id=connection_id); end $$;
create or replace function public.leave_guild(target_guild uuid) returns void language plpgsql security definer set search_path=public as $$ begin update public.guild_members set state='left',left_at=now() where guild_id=target_guild and user_id=auth.uid() and role<>'owner' and state='active'; if not found then raise exception 'active non-owner membership required'; end if; end $$;
revoke all on function public.respond_ally_invite(uuid,text) from public; grant execute on function public.respond_ally_invite(uuid,text) to authenticated;
revoke all on function public.remove_ally(uuid) from public; grant execute on function public.remove_ally(uuid) to authenticated;
revoke all on function public.leave_guild(uuid) from public; grant execute on function public.leave_guild(uuid) to authenticated;

create or replace function public.contribute_cooperative_boss(target_boss uuid,target_event uuid,requested_amount integer) returns integer language plpgsql security definer set search_path=public as $$ declare b public.cooperative_bosses%rowtype; ev public.activity_events%rowtype; prior integer; applied integer; begin select * into b from public.cooperative_bosses where id=target_boss for update; if b.id is null or not ((b.guild_id is not null and public.is_guild_member(b.guild_id,auth.uid())) or (b.pact_id is not null and public.is_pact_member(b.pact_id,auth.uid()))) then raise exception 'encounter access denied'; end if; select * into ev from public.activity_events where id=target_event and user_id=auth.uid() and type='quest_completed'; if ev.id is null then raise exception 'verified quest completion required'; end if; if exists(select 1 from public.cooperative_contributions where boss_id=target_boss and source_event_id=target_event) then return 0; end if; select coalesce(sum(amount),0) into prior from public.cooperative_contributions where boss_id=target_boss and user_id=auth.uid(); applied:=greatest(0,least(requested_amount,b.per_member_cap-prior)); if applied=0 then return 0; end if; insert into public.cooperative_contributions(boss_id,user_id,source_event_id,amount) values(target_boss,auth.uid(),target_event,applied); update public.cooperative_bosses set total=total+applied where id=target_boss; insert into public.cooperative_reward_claims(boss_id,user_id) select b.id,m.user_id from (select user_id,sum(amount) amount from public.cooperative_contributions where boss_id=b.id group by user_id) m where b.total+applied>=b.target and m.amount>=b.contribution_threshold on conflict do nothing; update public.cooperative_bosses set settled_at=coalesce(settled_at,now()) where id=b.id and total>=target; return applied; end $$;
revoke all on function public.contribute_cooperative_boss(uuid,uuid,integer) from public; grant execute on function public.contribute_cooperative_boss(uuid,uuid,integer) to authenticated;

create or replace function public.send_encouragement(target uuid,reaction text) returns uuid language plpgsql security definer set search_path=public as $$ declare event_id uuid; begin if reaction not in ('cheer','respect','well_done') or not public.accepted_allies(auth.uid(),target) then raise exception 'contact denied'; end if; if (select count(*) from public.encouragement_events where sender_id=auth.uid() and created_at>now()-interval '1 hour')>=5 then raise exception 'rate limit reached'; end if; insert into public.encouragement_events(sender_id,recipient_id,kind) values(auth.uid(),target,reaction) returning id into event_id; insert into public.notifications(user_id,kind,title,message,metadata) select target,'encouragement','An ally sent encouragement',replace(reaction,'_',' '),jsonb_build_object('social_peer_id',auth.uid()) from public.social_preferences where user_id=target and encouragement_notifications=true; return event_id; end $$;
revoke all on function public.send_encouragement(uuid,text) from public; grant execute on function public.send_encouragement(uuid,text) to authenticated;

alter table public.ally_connections enable row level security; alter table public.social_visibility_rules enable row level security; alter table public.blocks enable row level security; alter table public.accountability_pacts enable row level security; alter table public.pact_members enable row level security; alter table public.pact_commitments enable row level security; alter table public.guilds enable row level security; alter table public.guild_members enable row level security; alter table public.cooperative_bosses enable row level security; alter table public.cooperative_contributions enable row level security; alter table public.cooperative_reward_claims enable row level security; alter table public.focus_sessions enable row level security; alter table public.focus_participants enable row level security; alter table public.encouragement_events enable row level security; alter table public.social_preferences enable row level security; alter table public.reports enable row level security;
create policy "connection participants only" on public.ally_connections for select using(auth.uid() in (requester_id,addressee_id) and not public.social_blocked(requester_id,addressee_id));
create policy "request own ally" on public.ally_connections for insert with check(auth.uid()=requester_id and status='pending' and not public.social_blocked(requester_id,addressee_id));
create policy "own visibility rules" on public.social_visibility_rules for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id and public.accepted_allies(owner_id,ally_id));
create policy "own blocks" on public.blocks for select using(auth.uid()=blocker_id);
create policy "pact members only" on public.accountability_pacts for select using(public.is_pact_member(id,auth.uid()));
create policy "pact membership private" on public.pact_members for select using(user_id=auth.uid() or public.is_pact_member(pact_id,auth.uid()));
create policy "own pact commitments" on public.pact_commitments for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "active guild members only" on public.guilds for select using(public.is_guild_member(id,auth.uid()));
create policy "guild roster members only" on public.guild_members for select using(public.is_guild_member(guild_id,auth.uid()));
create policy "boss group members only" on public.cooperative_bosses for select using((guild_id is not null and public.is_guild_member(guild_id,auth.uid())) or (pact_id is not null and public.is_pact_member(pact_id,auth.uid())));
create policy "boss contributions group members" on public.cooperative_contributions for select using(exists(select 1 from public.cooperative_bosses b where b.id=boss_id));
create policy "own boss rewards" on public.cooperative_reward_claims for select using(user_id=auth.uid());
create policy "invited focus only" on public.focus_sessions for select using(host_id=auth.uid() or exists(select 1 from public.focus_participants p where p.session_id=id and p.user_id=auth.uid()));
create policy "own focus checkins" on public.focus_participants for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "encouragement participants only" on public.encouragement_events for select using(auth.uid() in (sender_id,recipient_id) and not public.social_blocked(sender_id,recipient_id));
create policy "own social preferences" on public.social_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own reports" on public.reports for insert with check(reporter_id=auth.uid());
