-- Part 6 RPG persistence. Apply with the Supabase CLI after `supabase link`.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;
create table public.profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, display_name text not null check (char_length(display_name) between 1 and 80), username text not null unique check (username ~ '^[a-zA-Z0-9_-]{3,32}$'), avatar_path text, title text not null default 'Awakened Developer', bio text not null default '' check (char_length(bio) <= 160), onboarding_completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.player_progression (user_id uuid primary key references auth.users(id) on delete cascade, level integer not null default 1 check (level >= 1), rank text not null default 'E', league text not null default 'Initiate I', xp bigint not null default 0 check (xp >= 0), next_level_xp bigint not null default 500 check (next_level_xp > 0), attribute_points integer not null default 0 check (attribute_points >= 0), coins bigint not null default 0 check (coins >= 0), keys integer not null default 0 check (keys >= 0), updated_at timestamptz not null default now());
create table public.player_attributes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, attribute_key text not null check (attribute_key in ('strength','intelligence','discipline','creativity','focus','communication')), value integer not null default 1 check (value >= 1), xp bigint not null default 0 check (xp >= 0), level integer not null default 1 check (level >= 1), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, attribute_key));
create table public.skill_definitions (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, category text not null, description text not null default '', created_at timestamptz not null default now());
create table public.player_skills (user_id uuid not null references auth.users(id) on delete cascade, skill_id uuid not null references public.skill_definitions(id) on delete restrict, xp bigint not null default 0 check (xp >= 0), level integer not null default 1 check (level >= 1), updated_at timestamptz not null default now(), primary key(user_id, skill_id));
create table public.achievement_definitions (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, category text not null, rarity text not null check (rarity in ('Common','Rare','Epic','Legendary','Mythic')), score integer not null default 0 check (score >= 0), created_at timestamptz not null default now());
create table public.player_achievements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, achievement_id uuid not null references public.achievement_definitions(id) on delete restrict, progress integer not null default 0 check (progress between 0 and 100), unlocked_at timestamptz, claimed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, achievement_id));
create table public.item_definitions (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, kind text not null, rarity text not null check (rarity in ('Common','Rare','Epic','Legendary','Mythic')), created_at timestamptz not null default now());
create table public.player_inventory (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, item_id uuid not null references public.item_definitions(id) on delete restrict, quantity integer not null default 0 check (quantity >= 0), equipped boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,item_id));
create table public.player_loadouts (user_id uuid primary key references auth.users(id) on delete cascade, title_item_id uuid references public.player_inventory(id) on delete set null, frame_item_id uuid references public.player_inventory(id) on delete set null, theme_item_id uuid references public.player_inventory(id) on delete set null, updated_at timestamptz not null default now());
create table public.quests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check (char_length(title) between 1 and 160), description text not null default '', category text not null, quest_type text not null check (quest_type in ('Daily','Weekly','Main Quests','Side Quests')), difficulty text not null check (difficulty in ('Easy','Medium','Hard','Legendary')), xp_reward integer not null check (xp_reward >= 0), coin_reward integer not null default 0 check (coin_reward >= 0), progress integer not null default 0 check (progress between 0 and 100), deadline timestamptz, status text not null default 'active' check (status in ('active','completed','draft','expired')), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.quest_objectives (id uuid primary key default gen_random_uuid(), quest_id uuid not null references public.quests(id) on delete cascade, label text not null, done boolean not null default false, position integer not null default 0, unique(quest_id, position));
create table public.habits (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, goal text not null, period text not null check (period in ('Morning','Afternoon','Evening','Anytime')), attribute_key text not null, difficulty text not null check (difficulty in ('Easy','Medium','Hard')), xp_reward integer not null check (xp_reward >= 0), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.habit_occurrences (id uuid primary key default gen_random_uuid(), habit_id uuid not null references public.habits(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, occurred_on date not null, progress integer not null default 0 check (progress between 0 and 100), status text not null default 'Pending' check (status in ('Pending','In Progress','Completed','Skipped','Missed')), completed_at timestamptz, rewarded_at timestamptz, unique(habit_id, occurred_on));
create table public.activity_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, type text not null, source_id text, route text not null, metadata jsonb not null default '{}'::jsonb, idempotency_key text not null, occurred_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(user_id,idempotency_key));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, event_id uuid references public.activity_events(id) on delete set null, kind text not null, title text not null, message text not null, route text not null default '/dashboard', metadata jsonb not null default '{}'::jsonb, read_at timestamptz, archived_at timestamptz, created_at timestamptz not null default now());
create table public.player_preferences (user_id uuid primary key references auth.users(id) on delete cascade, public_ranking boolean not null default true, show_avatar boolean not null default true, show_rank boolean not null default true, share_achievements boolean not null default true, share_skills boolean not null default true, share_quests boolean not null default false, share_habits boolean not null default false, settings jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());

create index on public.quests(user_id,status); create index on public.habits(user_id,active); create index on public.habit_occurrences(user_id,occurred_on desc); create index on public.activity_events(user_id,occurred_at desc); create index on public.notifications(user_id,created_at desc); create index on public.player_achievements(user_id); create index on public.player_inventory(user_id);
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at(); create trigger progression_updated_at before update on public.player_progression for each row execute function public.set_updated_at(); create trigger attributes_updated_at before update on public.player_attributes for each row execute function public.set_updated_at(); create trigger skills_updated_at before update on public.player_skills for each row execute function public.set_updated_at(); create trigger achievements_updated_at before update on public.player_achievements for each row execute function public.set_updated_at(); create trigger inventory_updated_at before update on public.player_inventory for each row execute function public.set_updated_at(); create trigger quests_updated_at before update on public.quests for each row execute function public.set_updated_at(); create trigger habits_updated_at before update on public.habits for each row execute function public.set_updated_at(); create trigger preferences_updated_at before update on public.player_preferences for each row execute function public.set_updated_at();

alter table public.profiles enable row level security; alter table public.player_progression enable row level security; alter table public.player_attributes enable row level security; alter table public.player_skills enable row level security; alter table public.player_achievements enable row level security; alter table public.player_inventory enable row level security; alter table public.player_loadouts enable row level security; alter table public.quests enable row level security; alter table public.quest_objectives enable row level security; alter table public.habits enable row level security; alter table public.habit_occurrences enable row level security; alter table public.activity_events enable row level security; alter table public.notifications enable row level security; alter table public.player_preferences enable row level security;
create policy "own rows" on public.profiles for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.player_progression for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.player_attributes for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.player_skills for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.player_achievements for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.player_inventory for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.player_loadouts for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.quests for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own objectives" on public.quest_objectives for all to authenticated using (exists(select 1 from public.quests q where q.id=quest_id and q.user_id=auth.uid())) with check (exists(select 1 from public.quests q where q.id=quest_id and q.user_id=auth.uid())); create policy "own rows" on public.habits for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.habit_occurrences for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.activity_events for select to authenticated using (user_id = auth.uid()); create policy "own rows" on public.notifications for select to authenticated using (user_id = auth.uid()); create policy "update own notifications" on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "own rows" on public.player_preferences for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace view public.public_leaderboard with (security_invoker = true) as select p.user_id, coalesce(nullif(pr.settings->>'publicName',''),p.display_name) as display_name, case when pr.show_avatar then p.avatar_path end as avatar_path, case when pr.show_rank then pg.level end as level, case when pr.show_rank then pg.rank end as rank, pg.xp, case when pr.share_achievements then (select count(*) from public.player_achievements pa where pa.user_id=p.user_id and pa.unlocked_at is not null) end as achievement_count from public.profiles p join public.player_preferences pr on pr.user_id=p.user_id and pr.public_ranking join public.player_progression pg on pg.user_id=p.user_id;

-- Shared catalogs are readable by authenticated players but remain server-managed.
alter table public.skill_definitions enable row level security; alter table public.achievement_definitions enable row level security; alter table public.item_definitions enable row level security;
create policy "read skill catalog" on public.skill_definitions for select to authenticated using (true);
create policy "read achievement catalog" on public.achievement_definitions for select to authenticated using (true);
create policy "read item catalog" on public.item_definitions for select to authenticated using (true);

-- Avatar objects are always stored under avatars/<auth.uid()>/<filename>.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('avatars', 'avatars', false, 2097152, array['image/jpeg','image/png','image/webp']) on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
create policy "avatar owners read" on storage.objects for select to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "avatar owners upload" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "avatar owners update" on storage.objects for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "avatar owners delete" on storage.objects for delete to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
