"use client";
import { ArrowDown, ArrowUp, CheckCircle2, Clock3, HeartPulse, Info, Pencil, RotateCcw, X } from "lucide-react";
import { useMemo, useState } from "react";
import type { Quest } from "../player-store";
import { capacitySummary, rankPrimeQuests, type DailyCheckIn, type DayMode, type RankedQuest } from "../daily-engine";

const defaults: DailyCheckIn = { minutes: 90, energy: 3, focus: 3, mode: "Balanced", note: "" };
export function DailyCommandCenter({ quests }: { quests: Quest[] }) {
  const [checkIn, setCheckIn] = useState<DailyCheckIn>(defaults); const [complete, setComplete] = useState(false); const [editing, setEditing] = useState(true); const [dismissed, setDismissed] = useState<string[]>([]); const [order, setOrder] = useState<string[]>([]); const [showWhy, setShowWhy] = useState(false);
  const ranked = useMemo(() => rankPrimeQuests(quests, checkIn).filter(item => !dismissed.includes(item.quest.id)), [quests, checkIn, dismissed]);
  const planned = useMemo(() => (order.length ? order.map(id => ranked.find(item => item.quest.id === id)).filter((item): item is RankedQuest => Boolean(item)) : ranked), [order, ranked]);
  const capacity = capacitySummary(planned, checkIn.minutes);
  const move = (id: string, direction: -1 | 1) => setOrder(current => { const source = current.length ? current : ranked.map(item => item.quest.id); const index = source.indexOf(id); const target = index + direction; if (index < 0 || target < 0 || target >= source.length) return source; const next = [...source]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  return <section className="daily-command game-panel" aria-labelledby="daily-command-title"><div className="daily-command-heading"><div><p className="eyebrow"><span /> ADAPTIVE DAY ENGINE</p><h2 id="daily-command-title">Daily command center</h2><p>Your plan adapts to today’s capacity—without changing your progress.</p></div><button onClick={() => setEditing(value => !value)} aria-expanded={editing}><Pencil size={15} /> {complete ? "Edit check-in" : "Set today’s capacity"}</button></div>
    {editing && <form className="daily-checkin" onSubmit={(event) => { event.preventDefault(); setComplete(true); setEditing(false); }}><label>Available minutes<input type="number" min="10" max="960" value={checkIn.minutes} onChange={event => setCheckIn({ ...checkIn, minutes: Math.max(10, Number(event.target.value) || 10) })} /></label><label>Energy <select value={checkIn.energy} onChange={event => setCheckIn({ ...checkIn, energy: Number(event.target.value) as DailyCheckIn["energy"] })}>{[1,2,3,4,5].map(value => <option key={value} value={value}>{value} / 5</option>)}</select></label><label>Focus <select value={checkIn.focus} onChange={event => setCheckIn({ ...checkIn, focus: Number(event.target.value) as DailyCheckIn["focus"] })}>{[1,2,3,4,5].map(value => <option key={value} value={value}>{value} / 5</option>)}</select></label><label>Day mode <select value={checkIn.mode} onChange={event => setCheckIn({ ...checkIn, mode: event.target.value as DayMode })}>{["Recovery","Balanced","Push"].map(value => <option key={value}>{value}</option>)}</select></label><label className="daily-note">Optional note<input value={checkIn.note} maxLength={120} placeholder="What should this plan account for?" onChange={event => setCheckIn({ ...checkIn, note: event.target.value })} /></label><div className="daily-checkin-actions"><button type="button" onClick={() => { setComplete(true); setEditing(false); }}>Skip for today</button><button type="submit"><CheckCircle2 size={15} /> Save check-in</button></div></form>}
    <div className="capacity-meter"><div><span><Clock3 size={15} /> Capacity</span><strong>{capacity.remaining >= 0 ? `${capacity.remaining} min remaining` : `${Math.abs(capacity.remaining)} min over capacity`}</strong><small>{checkIn.minutes} available · {capacity.planned} planned · {checkIn.mode} mode</small></div><i aria-hidden="true"><b style={{ width: `${Math.min(100, capacity.planned / checkIn.minutes * 100)}%` }} /></i></div>
    {capacity.exceeded && <div className="capacity-warning" role="status"><HeartPulse size={17} /><span>This plan is fuller than today’s available time. You can reduce scope, move an item, or pause without penalty.</span><button onClick={() => setOrder(current => current.slice(0, Math.max(0, current.length - 1)))}>Reduce plan</button></div>}
    <div className="prime-heading"><div><h3>Prime quests</h3><span>Now · Next · Later</span></div><button onClick={() => setShowWhy(value => !value)} aria-expanded={showWhy}><Info size={15} /> Why this plan?</button></div>{showWhy && <p className="plan-why">Recommendations are ranked deterministically by deadline, progress, difficulty, estimated duration, available time, and current energy. You can always reorder, dismiss, or replace them.</p>}
    <ol className="prime-list">{planned.length ? planned.map((item, index) => <li key={item.quest.id}><div className="prime-order"><b>{index === 0 ? "NOW" : index < 3 ? "NEXT" : "LATER"}</b><span>{index + 1}</span></div><div><h4>{item.quest.title}</h4><p>{item.reason}</p>{item.minimumVersion && <small><RotateCcw size={13} /> Minimum viable version available</small>}</div><strong>+{item.quest.xp} XP</strong><div className="prime-actions"><button onClick={() => move(item.quest.id, -1)} aria-label={`Move ${item.quest.title} earlier`} disabled={index === 0}><ArrowUp size={15} /></button><button onClick={() => move(item.quest.id, 1)} aria-label={`Move ${item.quest.title} later`} disabled={index === planned.length - 1}><ArrowDown size={15} /></button><button onClick={() => setDismissed(current => [...current, item.quest.id])} aria-label={`Dismiss ${item.quest.title}`}><X size={15} /></button></div></li>) : <li className="plan-empty">No eligible quests fit this day yet. Review your Quest Log or adjust capacity.</li>}</ol>
  </section>;
}
